import mongoose from "mongoose";

const wasteReportSchema = new mongoose.Schema(
  {
    // Which citizen submitted the report (links to the User model)
    reportedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // The waste category — matches the requirement's fixed list
    category: {
      type: String,
      enum: [
        "Household",
        "Industrial",
        "Medical",
        "Construction",
        "Water Body Pollution",
      ],
      required: [true, "Issue category is required"],
    },

    // The citizen's description of the issue
    description: {
      type: String,
      required: [true, "Description is required"],
      trim: true,
    },

    // Location: coordinates + resolved address (Maps auto-fills these later)
    location: {
      lat: { type: Number, required: [true, "Latitude is required"] },
      lng: { type: Number, required: [true, "Longitude is required"] },
      address: {
        type: String,
        required: [true, "Address is required"],
        trim: true,
      },
    },

    // Photo URLs (Cloudinary fills these later; up to 5)
    images: {
      type: [String],
      default: [],
      validate: {
        validator: (arr) => arr.length <= 5,
        message: "A report can have at most 5 photos",
      },
    },

    // Unique, human-readable case reference (auto-generated by the server)
    caseReference: {
      type: String,
      unique: true,
    },

    // The report's lifecycle status
    status: {
      type: String,
      enum: [
        "Reported",
        "Assigned",
        "Collector En Route",
        "Cleanup In Progress",
        "Resolved",
        "Closed",
      ],
      default: "Reported",
    },
  },
  {
    timestamps: true, // createdAt is the submission timestamp (requirement #6)
  },
);

const WasteReport = mongoose.model("WasteReport", wasteReportSchema);

export default WasteReport;
